name:                geo2d
version:             0.0.1
github:              "githubuser/geo2d"
author:              "Andrew McKnight"
maintainer:          "thedonk@gmail.com"
copyright:           "2021 Andrew McKnight"

extra-source-files:
- README.md
- ChangeLog.md
- Roadmap.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/geo2d#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - mtl
    - random
    - vector
    - ilist

executables:
  geo2d-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geo2d

tests:
  geo2d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geo2d
    - hspec
    - QuickCheck
